const questions = [
  {
    id: 1,
    type: "text",
    label: "Name of the child",
    name: "childName",
  },
  {
    id: 2,
    type: "number",
    label: "Age of the child (in months)",
    name: "childAge",
  },
  {
    id: 3,
    type: "radio",
    label: "Gender",
    name: "gender",
    options: ["Male", "Female", "Other"],
  },
  {
    id: 4,
    type: "number",
    label: "Height (in cms)",
    name: "height",
  },
  {
    id: 5,
    type: "number",
    label: "Weight (in kgs)",
    name: "weight",
  },
  {
    id: 6,
    type: "number",
    label: "Birth weight of the child",
    name: "birthWeight",
  },
  {
    id: 7,
    type: "radio",
    label: "Baby delivered after full term? Or pre-term?",
    name: "deliveryTerm",
    options: ["Full Term", "Pre-Term"],
  },
  {
    id: 8,
    type: "radio",
    label: "Mode of delivery",
    name: "deliveryMode",
    options: ["Vaginal delivery", "C-Section", "Others"],
  },
  {
    id: 9,
    type: "radio",
    label: "Did the baby cry soon after delivery?",
    name: "babyCry",
    options: ["Yes", "No"],
  },
  {
    id: 10,
    type: "text",
    label: "Any complications post-natal?",
    name: "complications",
  },
  {
    id: 11,
    type: "text",
    label: "What vaccinations done?",
    name: "vaccinations",
  },
  {
    id: 12,
    type: "text",
    label: "Developmental milestones (response time in months)",
    name: "milestones",
  },
  {
    id: 13,
    type: "radio",
    label: "Bowel movement",
    name: "bowelMovement",
    options: [
      "Poops twice daily without difficulty",
      "Poops once a day without difficulty",
      "Poops once a day but has difficulty (hard stools, constipation)",
      "Poops after every solid feed",
      "Has constipation more than twice a week",
      "Has constipation while/after travel",
      "Has constipation after any medication",
    ],
  },
  {
    id: 14,
    type: "radio",
    label: "Baby's sleep pattern",
    name: "sleepPattern",
    options: [
      "Sleeps undisturbed and at the same time mostly",
      "Difficult to fall asleep but sleeps at the same time",
      "Has disturbed sleep",
      "Cries in the middle of sleep but goes back to sleep",
      "Sleeping time is progressively reduced and playful",
      "Cranky before sleeping",
    ],
  },
  {
    id: 15,
    type: "radio",
    label: "Eating habits",
    name: "eatingHabits",
    options: [
      "Shows excitement when seeing food",
      "Happy to be fed with talking/storytelling",
      "Self-feeds whenever hungry",
      "Refuses to eat unless distracted",
    ],
  },
  {
    id: 16,
    type: "radio",
    label: "Skin condition",
    name: "skinCondition",
    options: ["Soft and smooth", "Dry and rashes", "Sensitive skin"],
  },
  {
    id: 17,
    type: "radio",
    label: "Vision health",
    name: "visionHealth",
    options: [
      "Looks normal and makes direct eye contact",
      "Squints sometimes at long distances",
      "Does not squint but looks only at long distances",
      "Looks far and near, makes eye contact, and follows bright/moving objects",
    ],
  },
  {
    id: 18,
    type: "text",
    label: "Any food preferences?",
    name: "foodPreferences",
  },
  {
    id: 19,
    type: "text",
    label:
      "Any food allergies? If yes, what food causes allergy and what are the reactions?",
    name: "foodAllergies",
  },
  {
    id: 20,
    type: "text",
    label: "Does the child refuse to eat any food? Mention the food items.",
    name: "foodRefusal",
  },
  {
    id: 21,
    type: "text",
    label:
      "Does the child have frequent infections? How often are antibiotics given?",
    name: "frequentInfections",
  },
  {
    id: 22,
    type: "text",
    label: "Any specific concerns about the baby?",
    name: "specificConcerns",
  },
  {
    id: 23,
    type: "text",
    label: "Any family history of health challenges or additional abilities?",
    name: "familyHistory",
  },
  {
    id: 24,
    type: "text",
    label: "Parent's Name",
    name: "parentName",
  },
  {
    id: 25,
    type: "email",
    label: "Parent's Email",
    name: "parentEmail",
  },
  {
    id: 26,
    type: "tel",
    label: "Parent's Phone Number",
    name: "parentPhone",
  },
  {
    id: 27,
    type: "text",
    label: "City",
    name: "city",
  },
];

// export default questions;
module.exports = questions;
